dist: bionic
sudo: required
language: cpp
compiler: gcc
script:
    - gcc -v && g++ -v && cmake --version
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake ..
    - make
